# Generated by Django 5.1.2 on 2024-12-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillupapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
