# Generated by Django 5.1.2 on 2024-12-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillupapp', '0002_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
    ]
